[#4 #8] flashcard routes
mfrydrychowiczTeam/learning-tool pull request #17
Opened 2021-02-22 18:04 UTC by lilareliga

na razie wstępny szkic, z wątpliwościami w komentarzach w kodzie

2021-02-22 20:14 UTC, Nebrakada commented on server/src/routes/flashcard.ts
> +    if(!flashcard) return res.status(404).send('The flashcard with the given ID was not found.');
przy if zawsze dawajmy { }, kiedyś może dorzucimy coś jeszcze log / debug. nie podkresla tego? nie ma na to reguly w eslint/linterze?

2021-02-22 20:22 UTC, lilareliga commented on server/src/routes/flashcard.ts
> +    if(!flashcard) return res.status(404).send('The flashcard with the given ID was not found.');
eslint działa jakoś dziwnie, bo miałam import modeli, które nie były zmerdżowane, i niektóre rzeczy mi wypisywał, ale autoformatowanie nie działało.

2021-02-23 00:14 UTC, CaptainObjective requested changes
Do merguj proszę developa. Trzeba też spojrzeć na tego twojego lintera bo coś tu ewidentnie nie działa jak należy

2021-02-23 00:14 UTC, CaptainObjective commented on server/src/routes/flashcard.ts
> +    const collection = await FlashcardCollection.findById(req.body.params.id);
chyba powinno być req.params.id

2021-02-23 00:14 UTC, CaptainObjective commented on server/src/routes/flashcard.ts
> +        FlashcardCollection: {//tu pytanie, czy nie potrzebujemy referencji w modelu flashcard
Z tego co widzę to narazie FlashcardCollection trzyma FlashCard[] nie bardzo widzę po co nam dodatkowa relacja w drugą stronę wiec powiedziałbym że całe FlashcardCollection tutaj nie potrzebne

2021-02-23 00:14 UTC, CaptainObjective commented on server/src/routes/flashcard.ts
> +        .then(result => {
jak już mamy funkcje async to bądźmy konsekwentni i piszmy await :D

2021-02-23 00:14 UTC, CaptainObjective commented on server/src/routes/flashcard.ts
> +    flashcard = await flashcard.save();
Nie bardzo rozumiem po co robimy ponowne przypisanie po zrobieniu save, nie wystarczy po prostu?:  
```suggestion
    await flashcard.save();
```

2021-02-23 00:14 UTC, CaptainObjective commented on server/src/routes/flashcard.ts
> +    const { error } = await validateFlashcard(req.body); //to dobrze zadziała przy patch? nie udało mi się wygooglować odpowiedzi
Nie odpowiem bo nie wiem jak wygląda req.body ;-P

2021-02-23 00:14 UTC, CaptainObjective commented on server/src/routes/flashcard.ts
> +    if(!flashcard) return res.status(404).send('The flashcard with the given ID was not found.');
Ja bym się nie upierał przy klamrach w ifach. Poradnik do JS mówi że tak można https://github.com/airbnb/javascript#blocks
Mając backend w node/express taka linia będzie pojawiać się bardzo często we wszystkich endpointach. Decyzje zostawiam wam do przegłosowania.

2021-02-23 00:14 UTC, CaptainObjective commented on server/src/routes/flashcard.ts
> +    }
Na ten fragment chciałbym bliżej spojrzeć jak już będą modele i baza danych podpięta. Wygląda jakbyśmy się wystawiali na [prototype pollution](https://portswigger.net/daily-swig/prototype-pollution-the-dangerous-and-underrated-vulnerability-impacting-javascript-applications)

2021-02-23 08:31 UTC, asiaziola commented on server/src/routes/flashcard.ts
> +    if(!flashcard) return res.status(404).send('The flashcard with the given ID was not found.');
ja nawet uważam że bez klamr jest bardziej elegancko

2021-02-24 18:03 UTC, CaptainObjective reviewed
Wygląda że jest git, dopisz proszę jakieś testy

2021-02-24 18:03 UTC, CaptainObjective commented on server/package.json
> +        "nodemon": "^2.0.7",
odinstaluj to proszę

2021-02-24 18:03 UTC, CaptainObjective commented on server/src/routes/flashcard.ts
> +        await collection['flashcards'].push(flashcard);
to chyba nie jest asynchroniczne, więc await jest zbędny

2021-02-26 10:43 UTC, lilareliga commented on server/package.json
> +        "nodemon": "^2.0.7",
@CaptainObjective  bez helmeta i jesta wywalały się testy na githubie:( I też jest problem z przejściem testów na githubie, ale to już wyższa szkoła jazdy. Lokalnie wszystko działa, coś trzeba zmienić tutaj...? Może chodzić o to, że dla testów łączy się z testową bazą na mongodb

2021-02-26 11:16 UTC, CaptainObjective commented on server/package.json
> +        "nodemon": "^2.0.7",
Chodzi o nodemona

2021-02-28 16:02 UTC, Nebrakada approved these changes

2021-02-28 16:12 UTC, CaptainObjective approved these changes

2021-02-28 16:20 UTC, merged